[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["kimaust"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
openai = "0.26.2"
overrides = "7.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
